### ISSUE TITLE
PThreads-Win32 support

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#123]
It's impossible to build with Pthreads-Win32 (`#define USE_PTH_THREADS`) due to the fact that
` wget_thread_t` is a `struct`. And one cannot assign a `struct` to `struct`. At least not in MSVC-2015.

Here are some pre-processed output from `src/host.c`:
```
  typedef struct {
    void *p;
    unsigned int x;
  } ptw32_handle_t;

  typedef ptw32_handle_t pthread_t;
  typedef pthread_t wget_thread_t;
```
Same problem in `src/wget.c` etc.

I think part of the fix is to use `pthread_equal(x,y)` for testing equality.

**Comment by rockdaboot** [comment]
> wget_thread_t is a struct

Not a pointer to a struct ? So they expose internal data ?

Somewhere I read about winpthread library as drop in replacement. Maybe that is an alternative ?

**Comment by rockdaboot** [comment]
Anyways, fork the repo and create an own branch. In this branch fix the code so that it works for you (threads and and anything else). Make small commits and that should be easy for us to merge and test on Linux (step by step) until we have a code base that works for us (POSIX/*nix) and you (Windows).

**Comment by gvanem** [comment]
I build w/o threads until Wget2 works. Now there some other serious problem causing no download at all. A `poll()` issue?
