### ISSUE TITLE
Improved test setup using libmicrohttpd

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#128]
I noticed that there are a few tests in `test-wget-1.c` that are commented out because the server we use doesn't support all the options (e.g. If-Modified-Since). Since we are writing a HTTP client, we should not have to implement a HTTP server as well. 

Instead, we could use another library (GNU Libmicrohttpd) which implements a web server as a library in C. This would require only our test suite to be dependent on this library. However, it provides us with a well tested web server which implements everything from RFC 2616 and RFC 7232-7236. What are everyone's thoughts on this? I think removing that server from the codebase will make Wget2 more stable since we will not be susceptible to bugs in the HTTP Server code.

**Comment by rockdaboot** [comment]
If-modified-since is a bad example, since this is trivial to implement (we just didn't do it).
But having several kinds of auth methods (digest, NTLM) would be nice.

However, it is a good idea - let's implement it in a separate branch after our first (alpha) release.
I would like to replace the libcurl test code in libmicrohttpd by libwget :smile:

**Comment by darnir** [comment]
> If-modified-since is a bad example, since this is trivial to implement (we just didn't do it).
> But having several kinds of auth methods (digest, NTLM) would be nice.

Agreed. That was just the first thing I noticed. But handling redirections and post requests including ones with binary data can all be handled by libmicrohttpd. So that would be a nice thing to have.

> However, it is a good idea - let's implement it in a separate branch after our first (alpha) release.
> I would like to replace the libcurl test code in libmicrohttpd by libwget :smile:

Agreed. We can do this post the alpha release. Also, I've spoken to the maintainer (Christian Grothroff) and he is interested in using libwget for its test suite as well once we have a stable release.

**Comment by dstw** [comment]
AFAIK, there are some benefits for developer on using libmicrohttpd by libwget. But, what is direct benefit that can affect end users?

**Comment by rockdaboot** [comment]
On Samstag, 1. April 2017 10:51:27 CEST Didik Setiawan wrote:
> AFAIK, there are some benefits for developer on using libmicrohttpd by
> libwget. But, what is direct benefit that can affect end users?

Depend on what "direct" is. The reason to have a test suite (as complete as 
possible) is to get a better code quality (less bugs, less security 
vulnerabilities, ...).
This (directly ?) effects the end user, don't you think so ?

Using libmicrohttpd instead of our own server code takes burden from us 
developers / maintainers. This gives us effectively more time to answer 
questions, add new features, fix bugs faster, ...
This also (directly ?) effects the end user.

Currently, we don't check HTTP authorization because we don't have server code 
for it. Also missing are checks for compression (we have gzip, deflate, xz/
lzma, bzip2, brotli), TLS subtleties, HTTP/2, ...
We do not support concurrent requests.
Things we did not found time to implement in our server code yet. Hopefully 
libmicrohttpd fills some of those gaps, but likely not all. So we will have to 
communicate with that project as well to ask for new features. Or we help out 
with patches...

In the end, both projects should benefit from GSOC. And hopefully more projects 
will benefit from an improved libmicrohttpd...

Regards, Tim

**Comment by dstw** [comment]
> The reason to have a test suite (as complete as
possible) is to get a better code quality (less bugs, less security
vulnerabilities, ...).

I see. The test suite is important part of a program that help us to ensure we have better quality code. The result, is a robust software. Hence, this impacts to every end users.
To get better test suite, our own current server code need improvisation, so we intend to **change** it with libmicrohttpd (need to remove own server code too). The drawback, we now add one more dependency to an external library. My question, what happen with the users when they don't have this requirement? Do we need to force this as prerequisite?

**Comment by rockdaboot** [comment]
On Samstag, 1. April 2017 11:44:47 CEST Didik Setiawan wrote:
> > The reason to have a test suite (as complete as
> 
> possible) is to get a better code quality (less bugs, less security
> vulnerabilities, ...).
> 
> I see. The test suite is important part of a program that help us to ensure
> we have better quality code. The result, is a robust software. Hence, this
> impacts to every end users. To get better test suite, our own current
> server code need improvisation, so we intend to **change** it with
> libmicrohttpd (need to remove own server code too). The drawback, we now
> add one more dependency to an external library. My question, what happen
> with the users when they don't have this requirement? Do we need to force
> this as prerequisite?

Depends on what a "user" is.
From my understanding a "user" installs a package with ready compiled binaries 
and/or docs (e.g. 'wget2'). This user executes e.g. 'wget2' to download or 
whatever. (S)he will never get in contact with any source code - so 
libmicrohttpd is *not* required as a prerequisite in this case.

Anyone who wants to build binaries (or docs) from the source code needs 
certainly the 'build' prerequisites which is far more and different to the 
'runtime' prerequisites.
These people need libmicrohttpd (when we changed out test suite) to check if 
the built binaries work as expected.
I assume these people to be experienced enough to deal with build 
prerequisites.

FYI, there are two different kinds of 'source code', source checked out of the 
repository and tarballs. The tarballs (for autotools projects) include a 
ready-to-run ./configure script (plus all it needs) while the sources from a 
repo do not (or should not) contain any automatically built files. There are 
more differences, but maybe a bit out of scope here.

A bit shorter:
- libmicrohttpd will be a 'build' prerequisite
- libmicrohttpd will *not* be a 'runtime' prerequisite

Regards, Tim

**Comment by dstw** [comment]
Interesting. You make it clear. I should not worry about this depedency problem anymore.
Thanks for the explanation.

**Comment by dstw** [comment]
In order to achieve this goal, we should modify function wget_test_start_server() and wget_test_stop_server() in tests/libtest.c. We call libmicrohttpd using this function. Could you give me some clue about how this process can be done? I need to breakdown this in order to fix my GSoC timeline. Thanks.

**Comment by darnir** [comment]
You really should be asking these questions on the wget and libmicrohttpd mailing lists together. That will ensure that more people see your messages and give them a chance to answer. This repository is watched by far fewer people.

Anyways, what exactly are you looking for? libmicrohttpd is a library. You need to set it up in the `wget_test_start_server()` method and then pass on the address on which the server is listening to actual tests. In `wget_test_stop_server()`, you tear down the server and end the tests.
