### ISSUE TITLE
Progress bar: Visual Bug

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#131]
There is a visual bug in the progress bar that can be recreated using the following commands:

```
$ clear
$ wget2 --progress bar example.com
```

You will see that the first line of the console gets scrolled up as a result of the command. This should not happen. However, we don't see any weird behaviour when wget2 is not the first command executed on a clean terminal. This implies that the bug is caused due to excessive cursor movements.

**Comment by darnir** [comment]
Has anyone else been able to reproduce this? If yes, it's a bug we need to look into, else it may be my environment screwing things up and I must look into that

**Comment by rockdaboot** [comment]
This happens when we scroll the screen one up (in wget_bar_set_slots()).
Same if an error occurs: we need one line space above the scroll bar area, thus scrolling the whole screen one up, print the error msg (hopefully on one line) and redraw the scroll bar area.

It should be possible to place the cursor at the bottom of the scroll area, print \n (only scroll up the screen if needed) and restore the old cursor position. I start testing that...

**Comment by rockdaboot** [comment]
When the screen becomes scrolled (cursor being near the bottom of the screen), cursor position (row) stays the same. Adding new lines without scrolling updates the cursor position (row).
To handle both cases gracefully, we need to read the cursor position after adding the progress area. AFAICS, this can not be done in a system independent way.

I personally won't spend any more time into the scroll bar, since progress bar code already wasted lot's of time without adding functionality. IMO, this has absolutely low priority.

**Comment by rockdaboot** [comment]
Just for reference: http://www.linuxquestions.org/questions/programming-9/get-cursor-position-in-c-947833/

**Comment by darnir** [comment]
I agree. I've spent enough time on this visual glitch which doesn't get us much. Just wondered if you knew something more about why it happened.

There is also the issue that the current implementation will not work on Windows. In fact I could not find any library that can perform cursor movements on Windows terminals. I'll close this issue for now and we'll look into it again at some point if enough people complain.
