### ISSUE TITLE
[Win32] Warning for signed SOCKET 

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#169]
Even with the POSIX *shoehorning* in Gnulib, the `FD_SET()` macro still takes signed `SOCKET`. And Gnulib seems to have no replacement for `FD_SET()` (only `FD_ISSET()`). Hence clang-cl warns:
```
libwget/io.c(243,2):  warning: comparison of integers of different signs: 'SOCKET' (aka 'unsigned int') and 'int'
      [-Wsign-compare]
        FD_SET(fd, &fdset);
        ^~~~~~~~~~~~~~~~~~
f:\ProgramFiler-x86\WindowsKits\Include\10.0.10586.0\um\winsock2.h(161,50):  note: expanded from macro 'FD_SET'
        if (((fd_set FAR *)(set))->fd_array[__i] == (fd)) { \
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~
1 warning generated.
```
I could easily tolerate it, but could we make a `wget2_socket_t`?

Another signed warning while I'm at it:
```
libwget/net.c(727,79):  warning: passing 'size_t *' (aka 'unsigned int *') to parameter of type 'socklen_t *'
      (aka 'int *') converts between pointers to integer types with different sign [-Wpointer-sign]
  ...= accept(parent_tcp->sockfd, parent_tcp->bind_addrinfo->ai_addr, &parent_tcp->bind_addrinfo->ai_addrlen)) != -1) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
f:/MingW32/src/Gnu/GnuLib/lib\sys/socket.h(338,62):  note: passing argument to parameter 'addrlen' here
                  (int fd, struct sockaddr *addr, socklen_t *addrlen));
                                                             ^
```

**Comment by rockdaboot** [comment]
FD_SET takes an integer (defined by POSIX) and we give an integer. That has to be fixed somewhere else - I am not going to break proper code just to silence another one's bug.
The message says, the problem is in winsock2.h. 

The second looks like the same: bind_addrinfo is a struct addrinfo which has a member 'socklen_t ai_addrlen' (also conforming to POSIX). This holds true for Linux headers and gnulib headers. So I am not sure where the problem is (definition of struct addrinfo). Can you check your headers for this struct to be correct ? Also, semantically it seems correct. It is just a syntax warning.

**Comment by gvanem** [comment]
Ok, I'm adding `-Wno-sign-compare` and `-Wno-pointer-sign` to my CFLAGS. 
This suppresses these 2 warnings. Closing.
