### ISSUE TITLE
Config files' location should be user-overridable

### ISSUE THREAD

**Issue by juaristi** [rockdaboot/wget2#22]
In wget, we have `$WGETRC` and `--hsts-file` so that we can tweak where to read those files from.
I'm working on something similar for wget2. I propose:

 - `--hsts-file` for the HSTS file, or `~/.wget-hsts` otherwise. Should be backwards-compatible with wget.
 - `--ocsp-file` for the OCSP file, or `~/.wget-ocsp` otherwise. AFAIK there's no OCSP support in wget.
 - `$WGETRC` for the user config file, or `~/.wgetrc` otherwise. This is backwards-compatible with wget.

**Comment by darnir** [comment]
There's already a `--hsts-file` and `--ocsp-file` option.

The only thing missing is the `$WGETRC` env variable. The `--config-file` option to override is also backwards compatible with Wget

**Comment by juaristi** [comment]
Thanks.
You're right, they're there and work well. I'm still finding my way on the code base.

I didn't know about the `--config-file` option. Now, this makes me think, is an env variable really necessary? I remember someone's concerns on the wget mailing list about that not so much ago. Someone said that env variables are not good user experience because you have to remember they're there. I cannot find the thread in the archives. What's the point of having a command-line option and an env var together?

**Comment by rockdaboot** [comment]
I guess, the only point is to be backward compatible.
I can't judge how many people rely on it, but why not supporting it ?

**Comment by darnir** [comment]
The reason for not supporting it is simplicity in code.

Also, currently Wget seems to prefer the file in WGETRC over one specified on the command line. This, IMO is wrong behaviour since something explicitly mentioned on the command line should always override an env variable.

So, if we're planning on supporting this **only** for backward compatibility, do we fix the behaviour and break compatibility or retain the buggy behaviour?

Personally, I feel if we're going to break compatibility, might as well, not support this at all. Unless someone eventually explicitly asks for it. Extending will not be difficult.

**Comment by darnir** [comment]
At this point, this bug is a dependent on how we decide to move forward with #24 
So, I'm marking this as a duplicate and closing it.
