### ISSUE TITLE
--trust-server-names skiping spaces in filename

### ISSUE THREAD

**Issue by shadowzoom** [rockdaboot/wget2#235]
Hi there, i'm using
`wget2 --no-check-certificate --content-disposition  --header "Cookie: sessionid=123" https://example.com/page.px?fileid=123 --trust-server-names --debug`
But wget saving wrong filename and skipping spaces.
Server response
`Content-disposition: attachment; filename=my 1st image.jpg`
wget2 saved this like "my" and not "my 1st image.jpg"

**Comment by rockdaboot** [comment]
Hey, if there are white space in the filename, the server *must* enclose it with double quotes. Otherwise the space is taken as delimiter to the next tag/key. In this case it would be '1st' - as this is unknown to wget2, we ignore it (and also the following words).

So the server should have said
`Content-disposition: attachment; filename="my 1st image.jpg"`
