### ISSUE TITLE
Make a release for windows

### ISSUE THREAD

**Issue by Dominiquini** [rockdaboot/wget2#292]
The new version (2.1.0) don't have any windows builds released!

Thanks.

**Comment by rockdaboot** [comment]
The only way for me to make a Windows build is using cross-compilation from Linux, which seems to comes with some pitfalls. The wget2.exe that I can build has an issue with multi-threading when running under wine (a windows emulator).

Better not ship anything rather than a broken wget2.exe. Sorry for that inconvenience.
If you have a chance, there is WSL2 and CygWin.
