### ISSUE TITLE
wget2 + api.github.com displaying is a mess if compared with wget

### ISSUE THREAD

**Issue by ivan-hc** [rockdaboot/wget2#314]
Since the Fedora 40 team has decided to adopt wget2 by default at the expense of the already established wget, some users have complained about the uselessness of the scripts on my repository that rely heavily on wget. I don't know much about wget2, so I would like to know if there is a way to achieve this

![326130358-dec4b61e-b837-4ee7-a2d7-e68430381d6b](https://github.com/rockdaboot/wget2/assets/88724353/13e30cf2-ded2-48d4-b49e-bd5e79a6bede)

instead of this

![326130992-c80be00e-7c63-472b-90dd-60fcde408959](https://github.com/rockdaboot/wget2/assets/88724353/c5b7ec9a-8785-4d41-98a8-96d46e63adb2)

without having to rewrite almost 2000 scripts in my repository (and I don't think I'm the only one facing this issue).

I trust in your good will. Thanks

https://github.com/ivan-hc/AM/issues/496

**Comment by Samueru-sama** [comment]
The quick fix right now would be building and installing wget in the host machine as detailed [here
](https://github.com/ivan-hc/AM/issues/496#issuecomment-2080239651)

Where that wget gets installed would need to be first in `$PATH`, so if it is `$HOME/.local/bin` which is a XDG compliant location, this rule would need to be exported in your zshrc or bashrc: 

`export PATH="$HOME/.local/bin:$PATH"`

I can also setup a CI for building wget appimage/binary on ubuntu that should work on fedora and newer if needed that AM can install.

And to get AM to be able to install on fedora40, we can change the install script to do a `git clone` of the main repo and move the module dirs to its right location.


-----------------------------------------------------------

Long term I think we will need to start shipping AM as an appimage with its dependencies built in (wget and zsync), that way we can control against these issues better in the future.  

After archlinux removed the Glibc eac patch recently because it was only like 3 games that needed so they said fuck it (which one is brawhalla which I've played lmao) I've learned that hard way to not rely on my distro for anything, I even recently had to downgrade cmake on my PC because I ran into a bug that prevents me from building packages, which I can't report because the bloody cmake website doesn't send the registration email kek.

**Comment by rockdaboot** [comment]
Neither Wget nor Wget2 manipulate the JSON data. It the decision of the server to send different responses for Wget and Wget2.

The solution is to "disguise" Wget2 as being "Wget". This can be done in several ways:
1. for a single invocation, add `--user-agent="Wget/1.24.5"` to the command line (the version doesn't matter)
2. to set this permanently for a single user, put the option into `$XDG_CONFIG_HOME/wget/wget2rc`, `$HOME/.config/wget/wget2rc` or `$HOME/.wget2rc`. Alternatively, use `--config` to specify the location of your config file or set the `WGET2RC` environment variable to the config file path.
3. set the option system-wide in the global config file, which can be `/etc/wget2rc` or somewhere else (depends on your Linux contribution).

This kind of browser sniffing that you run into is normally done to help the user, but often backfires.

Another option for your case is piping the output through `jq` (` wget ... | jq -r '.'`). That way you are independent of the JSON whitespacing in the server response.

Feel free to re-open if you still run into the same issue.

**Comment by ivan-hc** [comment]
@rockdaboot thank you for the reply. I have to say though that adding flags and fiddling with external configuration files is not the best of approaches. I see it more as a way around the problem.

There are many projects, even inactive but still used (like mine could be in the future) that still rely on the old "wget", and I believe that a fundamental tool like that should be replaced by a 100% backwards compatible successor, don't you think?

I don't think I'm the only one tinkering with the github API, so a step like that is quite a detriment. And we know very well that what passes for Fedora becomes "law" in the Linux world.

If you can't fix the problem programmatically, you should at least contact the github team, you or whoever, to report this change, or tons of other projects will end up useless, like mine, on Fedora 40.

You could also have a configuration file created automatically, in $HOME, upon first use, to list settings that the user can easily change, or restore by deleting the file and using wget2 again.

**Comment by rockdaboot** [comment]
@ivan-hc I really feel your troubles and I am pretty concerned about the Fedora decision. It was the first time I heard about it, and now fear to see lot's of incoming issues. I never got any money or other support for the Wget2 project and so won't have time to spend more than 2h per week or so on it.

Wget2 was meant to be installed in parallel to wget, because there is no 100% compatibility - and that was never the goal. It was meant to adopt some state-of-the-art web techniques that are definitely breaking some edge cases. E.g. parallel downloads break things under some circumstances (think of connection quotas). Also, we want to drop some old stuff, e.g. FTP will never be part of Wget2 (ok, never say never =)).

You just ran into one of *many* possible corner cases that break compatibility. Luckily, that was easy to find out, my first guess hit the nail. But here are open issues that are not easily fixable at all.

Just one tip from my side regarding JSON parsing: do not use grep!!! JSON is a flexible format that can change any time - it's the provider's / server's decision as you have seen. Ideally, use `jq`, really. It's not a work-around, it is the proper way to deal with JSON when you are using bash scripts.

I personally won't contact Fedora/RedHat because they are free to do whatever they like to do with Wget or Wget2. Maybe they have good reasons, maybe not. If they run into issues with user complaining, they possibly will contribute to the project. That would be a win for everybody.

What I can do is thinking about changing the user-agent string to "Wget/2.x.y". At least it seems to help with the Github API.
