### ISSUE TITLE
No CAs were found error on Windows 11

### ISSUE THREAD

**Issue by rahaaatul** [rockdaboot/wget2#335]
Wget2 says this:

```shell
No CAs were found in 'C:\ProgramData/ssl/ca-bundle.pem'
```

then proceeds to do the task.

What's the issue? How do fix this?

**Comment by rockdaboot** [comment]
I am not using Windows myself, so can only ask general questions.
Do you have a directory `C:\ProgramData\ssl`? If yes, what is the content?

The code to find the CA certificates on Windows has been contributed by @mitchcapper. Maybe they can help?

**Comment by rahaaatul** [comment]
> I am not using Windows myself, so can only ask general questions. Do you have a directory `C:\ProgramData\ssl`? If yes, what is the content?

No. I do not have the `ssl` folder in `ProgramData` directory.

**Comment by rockdaboot** [comment]
When you say "then proceeds to do the task.", does it mean the https link is downloaded as expected and that the message "No CAs were ..." is just annoying. Or does wget2 failes to download via https?

**Comment by rahaaatul** [comment]
> When you say "then proceeds to do the task.", does it mean the https link is downloaded as expected and that the message "No CAs were ..." is just annoying. Or does wget2 fail to download via https?

Yes, that's correct. `Wget2` successfully downloads the file from the HTTPS link. While the "No CAs were ..." message isn't particularly bothersome, I'm just curious about its cause.

**Comment by mitchcapper** [comment]
There is no standard ca file in Windows.  By default there is the native certificate store but most non-windows first applications don't use this.   Applications/browsers sometimes include their own cafile.   We generate that message because of a common issue with curl/wget (1.0) on windows where you not only can't validate SSL certs by default but may have no idea where to even put a CA file on the system for the app to pick it up without a custom command line option.

In terms of why `%ProgramData%/ssl`  is the folder chosen:
%AppData% style folders are user specific but %ProgramData% is system wide, ca files would seem to be most fitting for system wide.   Installing in %system32%/windows/Program Files seemed less fitting.   Further gnutls also uses %programdata% by default.

**Comment by rahaaatul** [comment]
I'd also like you to pay attention here:

`C:\ProgramData/ssl/ca-bundle.pem`

Look at the slashes, backward and forward. I don't think that's ideal? In windows it should be all backward slashes.

**Comment by rahaaatul** [comment]
> We generate that message because of a common issue with curl/wget (1.0) on windows where you not only can't validate SSL certs by default but may have no idea where to even put a CA file on the system for the app to pick it up without a custom command line option.

Is there a possibility to force wget2 to not show this message?

**Comment by mitchcapper** [comment]
Windows happily will take the slashes in anyway you like.  My recommendation would be as gnutls able to fallback to the system certificate store on windows we should only show the message if the CA file explicitly exists.  The corresponding gitlab issue is:
https://gitlab.com/gnuwget/wget2/-/issues/663

**Comment by rockdaboot** [comment]
Fixed by 7aa492f8227b59fe8da4f84b88e8848cbcf40a18

**Comment by mitchcapper** [comment]
@zotabee what does `wget2 --version` say? thanks
