### ISSUE TITLE
Valgrind tests don't work on Travis

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#57]
I tried setting up Valgrind tests on Travis, by setting the --enable-valgrind-tests configure parameter, This works locally for me, but on travis, the tests are always executed without valgrind. 

Can someone please take a look at what it wrong with Travis?

**Comment by darnir** [comment]
My changes can be seen here: https://github.com/darnir/wget2/commits/test-valgrind

**Comment by rockdaboot** [comment]
Just a few comments:
1. set -e didn't work for me, that's why i am using '|| exit 1' (right now I can't remember what it *exactly* was)
2. are you sure valgrind is available on mac os x and installed and working ? If not, don't enable it on mac osx .
3. how can I see your travis results ?

**Comment by rockdaboot** [comment]
What me puzzles: I copied your branch and pushed it to rockdaboot/wget2 (branch test-valgrind) - it works fine: https://travis-ci.org/rockdaboot/wget2/branches

**Comment by darnir** [comment]
Not really. If you look at the actual Travis log, you'll see that the tests were executed without Valgrind.

**Comment by rockdaboot** [comment]
Linux and MacOSX Travis behave differently. I just added some 'grep -i valgrind'

On Linux, there seems to be an old version of auto* tool. Valgrind is found and TESTS_ENVIRONMENT is set up correctly:
```
configure:43327: checking for valgrind
configure:43343: found /usr/bin/valgrind
Makefile:HAVE_VALGRIND = yes
Makefile:VALGRIND_TESTS = 1
Makefile.in:HAVE_VALGRIND = @HAVE_VALGRIND@
Makefile.in:VALGRIND_TESTS = @VALGRIND_TESTS@
tests/Makefile:HAVE_VALGRIND = yes
tests/Makefile:VALGRIND_TESTS = 1
tests/Makefile:AM_TESTS_ENVIRONMENT = export VALGRIND_TESTS"=1";
tests/Makefile.am:AM_TESTS_ENVIRONMENT = export VALGRIND_TESTS"=@VALGRIND_TESTS@";
tests/Makefile.in:HAVE_VALGRIND = @HAVE_VALGRIND@
tests/Makefile.in:VALGRIND_TESTS = @VALGRIND_TESTS@
tests/Makefile.in:AM_TESTS_ENVIRONMENT = export VALGRIND_TESTS"=@VALGRIND_TESTS@";
```
That means that getenv() in tests/test.c, Line 818 returns something unexpected.
I printed out all vars from char **environ, and there is no VALGRIND_TESTS variable.
I guess this is due to the old auto* versions.

On MacOSX, valgrind is not found.
```
checking for valgrind... no
```
This means AC_CHECK_PROG fails.
I don't know how to set the path correctly with ./configure.

**Comment by rockdaboot** [comment]
'export VALGRIND_TESTS=1' for linux seems to work (but the output has > 10000 lines, so travis aborts with error)

**Comment by rockdaboot** [comment]
And 
```
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi
```
lets valgrind tests work on mac osx.

**Comment by rockdaboot** [comment]
OSX throws out tons of valgrind (false ?) positives.
In the net people say these are false positives, so I won't spend too much time into investigations and just drop valgrind testing for osx. WDYT ?

**Comment by darnir** [comment]
We could quickly auto-generate a suppressions file for OSX. And pass it to
valgrind on that platform.

Although, let me take a quick look. Maybe the issue is the same that we had
for Wget? Falsa positives from the SSL libs?

On 24 January 2016 at 16:47, Tim Rühsen <notifications@github.com> wrote:

> OSX throws out tons of valgrind (false ?) positives.
> In the net people say these are false positives, so I won't spend too much
> time into investigations and just drop valgrind testing for osx. WDYT ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rockdaboot/wget2/issues/57#issuecomment-174310916>.
>



-- 
Thanking You,
Darshit Shah

**Comment by rockdaboot** [comment]
We have no Mac OS X dependent code in Wget2, so why should we do valgrind tests here when we do them already on Linux successfully ? Anyone doing a valgrind test on his own Mac will likely need different suppressions for valgrind... (because of different software/library versions). To me this smells like doing lots of maintaining for almost no bargain. If we really introduce OSX incompatible code changes, these should come out with non-valgrind tests.
But however, if you like to add valgrind suppressions, go for it.
If you find some time, investigating into AppVeyor (Windows testing) and/or MinGW cross-compilation testing with wine (compilation worked a while ago). It would be really cool if we could generate a working wget2 windows exe file (or .zip with DLLs in it).
I will spend my time into fixing the open bugs and completing the docs...

**Comment by rockdaboot** [comment]
@darshit Can we close this or is there any work in progress ?
