### ISSUE TITLE
Use AppVeyor or Gitlab CI for Windows building/testing

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#61]

**Comment by darnir** [comment]
For this we first need the exact steps to build on Windows. Then we can write an appveyor.yml file to test builds.

I've looked into this for Wget some time ago. But the lack of time / a WIndows machine meant I didn't get too far. Will take a look again around the end of February, when I should have some time on my hands.

**Comment by rockdaboot** [comment]
This is low priority. If someone wants us to support Windows, this person should do the (initial) main work. BTW, I am not sure if we want Windows support outside MinGW/MSYS and/or Cygwin !?

**Comment by darnir** [comment]
True. I've been looking into this just as a random personal interest.

And I agree, support outside of MinGW or CygWin should not be considered. The state of C compilers on Windows is pretty pathetic. And we should be able to use newer standards of C than be stuck around because of that.

Though I'm not sure how well Appveyor integrates with MinGW or CygWin environments. Till someone comes asking, we can probably shelf this issue.
