### ISSUE TITLE
Add OCSP "Must-Staple"

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#75]
https://www.grc.com/revocation/ocsp-must-staple.htm
https://tools.ietf.org/html/rfc7633
1. If stated by the new cert extension, the server _must_ send a stapled OCSP record. If the server doesn't -> hard-fail.
2. New HTTP response header "Must-Staple:", similar to HSTS. On first contact put the domain + expire into a database. On successive contacts we _must_ expect a stapled OCSP record, else hard-fail (or contact OCSP responder and than hard-fail on error).

**Comment by juaristi** [comment]
I'm puzzled with this.

Everybody seems to favour option 1 (use a TLS extension) since I'm not seeing discussions on `Must-Staple` header (other than [here](https://www.ietf.org/mail-archive/web/tls/current/msg10351.html)) and also RFC 7633 does not mention it at all. Firefox [seems to only implement option 1](https://wiki.mozilla.org/CA:ImprovingRevocation#OCSP_Must-Staple) also.

openssl does not support it until 1.0.1, and I had to roll forward to "experimental" (Debian) in order to get it. The same happens with GNUTLS. It is supported in 3.5.1, which is also in experimental.

Finally, looks like GNUTLS deals with it automatically. From the [docs](http://www.gnutls.org/manual/gnutls.html#OCSP-stapling):

> In addition, since GnuTLS 3.5.1 the client will consider the [RFC7633] OCSP-Must-staple certificate extension, and will consider it while checking for stapled OCSP responses. If the extension is present and no OCSP staple is found the certificate verification will fail and the status code GNUTLS_CERT_MISSING_OCSP_STATUS will returned from the verification function.

RFC 7633 is dated October 2015. I think this should wait until, at least, we have this in the stable branch. WDYT?

**Comment by rockdaboot** [comment]
Thanks for looking into the issue, Ander.

The Must-Staple TLS extension is slowly coming, e.g. via Let's Encrypt - you just have to request it.

Looks like option 1 is being handled within the TLS libraries. We only have to provide some diagnosis messages, e.g. in print_ocsp_verify_res() and in _verify_certificate_callback().

About option 2 I read some discussions on Twitter a while ago. Currently we just have to keep an eye on it - no need to implement it as long as servers doesn't use it.

**Comment by juaristi** [comment]
FYI the current Wireshark stable cannot dissect the TLS extension either.
