### ISSUE TITLE
Add support for pre/post download scripts

### ISSUE THREAD

**Issue by srussel** [rockdaboot/wget2#80]
I would like an option for wget2 to run a script before each download. The exit status determines whether to download the file. Similar to the -user_condition option in pavuk.

In pavuk, a number of options are passed to the script:
-url <URL to be downloaded>
-parent <parent URL>
-level <level of the URL>
-size <size of requested URL>
-date <date of URL>

Alternatively the arguments could be passed via environment variables similar to transmissionbt post download scripts. This would be better as it does not require the script to parse the command line.

Pavuk also has a -follow_cmd option that runs a script after each file has been downloaded.

**Comment by rockdaboot** [comment]
I agree, this feature is something we want to have.
Someone made a similar request for Wget, see https://savannah.gnu.org/bugs/index.php?45803

Starting a process for each URL is a *very* slow approach. 
And when parsing HTML/CSS/RSS/Sitemaps things like parent and level won't change. size and date are not known at that moment. So we could just write a list of all URLs (e.g. line by line) to the script together with a unique ID. The script could just print the IDs of all URLs that should be downloaded. With this approach we reduce the number of spawns/forks dramatically.

**Comment by juaristi** [comment]
Making things worse... ;D What about having an event-based public API where a user can define some functions which will get called whenever something happens? This user-defined functions would get fed to wget with a shared library. MySQL has [similar functionality](http://dev.mysql.com/doc/refman/5.7/en/adding-udf.html), which IMO is not really useful for anyone but crackers, who use it to run arbitrary code on the target when exploiting SQL injection flaws. But in wget, since it runs in client side and on demand, it might provide some real usefulness. I saw something like this listed in an early to-do list.
